resources:
  pipelines: 
    - pipeline: _Build Cloud Account Id Artefacts
      source: Build Cloud Account Id Artefacts 3.0
    - pipeline: _Lansa Images - Cookbooks
      source: Build Image Release Artefacts 3.0
  repositories:
    - repository: _lansa_azure-quickstart-templates
      name: lansa/azure-quickstart-templates
      type: github
      ref: support/scalable
      endpoint: robe070

variables:
  - group: Template Parameters
  - group: SKU Versions
  - group: Image Names
  - group: Azure Logins
  - group: Git Repos
  - name: CookbooksSource
    value: $(Pipeline.Workspace)\cookbooks
  - name: jpnLanguage
    value: JPN
  - name: ResourceGroupName
    value: BakingDP
  - name: SubscriptionId
    value: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3

stages:
  - template: AzureDevOps\templates\AzureTestCloudAccountIdImage.yml
    parameters:
      stageName: v15
      stageDisplayname: v15
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V15'], 'True'), eq(variables['Build-all'], 'True'))
      setGateVariableScriptPath: 'azure_set_gate_variable_cloud_account_id.ps1'
      msiURL: $(msiURLv15)

  - template: AzureDevOps\templates\AzureTestCloudAccountIdImage.yml
    parameters:
      stageName: v14sp2
      stageDisplayname: v14sp2
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V14SP2'], 'True'), eq(variables['Build-all'], 'True'))
      setGateVariableScriptPath: 'azure_set_gate_variable_cloud_account_id.ps1'
      msiURL: $(msiURLv142)

  - template: AzureDevOps\templates\AzureTestCloudAccountIdImage.yml
    parameters:
      stageName: v15scalable
      stageDisplayname: v15-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V15-scalable'], 'True'), eq(variables['Build-all'], 'True'))
      setGateVariableScriptPath: 'azure_set_gate_variable.ps1'
      msiURL: $(msiURLv15)

  - template: AzureDevOps\templates\AzureTestCloudAccountIdImage.yml
    parameters:
      stageName: v14sp2scalable
      stageDisplayname: v14sp2-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V14SP2-scalable'], 'True'), eq(variables['Build-all'], 'True'))
      setGateVariableScriptPath: 'azure_set_gate_variable.ps1'
      msiURL: $(msiURLv142)
